### ISSUE TITLE
Feature request: Add seperator between "semantic" and tailwind classes

### ISSUE THREAD

**Issue by skttl** [theron-wang/Class-Hide#2]
In my code, I sometimes add a "semantic" class, primarily to identify the component, but also sometimes to add some custom css to that.

I then seperate this from the utility classes, by adding a symbol like ~ or | .

Would be nice if this extension could exclude everything before a configured string (eg. ~ or | , but make it configurable, maybe even a regex) when hiding stuff.

So I could have

```html
<div class="my-card ~ ...">
    <div class="..."></div>
    <div class="my-card__headline ~ ..."></div>
</div>
``` 

If the configured string is not found in the class list, it should just hide everything (or what it does according to the config).

**Comment by theron-wang** [comment]
Thanks. Added in 1.2.0. You can set a character/string in the Delimiter field in settings. One caveat, however; if you are using this with the Tailwind extension, class sorting might mess with the location of the ~. Although, since you are using the delimiter to separate semantic classes from Tailwind classes, it shouldn't be a big issue since your Tailwind classes are probably after it anyway. Let me know if you need anything else!
